### ISSUE TITLE
Collection Metadata is incorrect

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/holaplex#122]
The collection minting tool isn't properly setting the collection data. According to the metadata json uri structure, the collection key needs to be  two key value pairs, not a string.  https://docs.metaplex.com/nft-standard

ex: 
```{{ "collection": {"name": "Solflare X NFT","family": "Solflare"}}}```

https://github.com/holaplex/holaplex/blob/675b05ffafb9a76b3c633dc93e54b7b6531d09d8/pages/nfts/new.tsx#L66 This looks like the culprit

**Comment by sjc5** [comment]
@dandlezzz – PR addressing this issue: #123
