### ISSUE TITLE
Add Badge for Secondary Sales in disco tool & Listing card redesign

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/holaplex#166]
Let's let users discover secondary sales more easily. A well designed badge and a filter option would help a ton!

**Comment by kristianeboe** [comment]
More specifically this will add(to the discovery tool):
- a new "Secondary" filter
- a badge to listings who are identified as a secondary sale

**Comment by bellebellesol** [comment]
https://www.figma.com/file/zlNK0tnw0yJgYLEV3kCFkv/Listing-card-badges-%2B-improvements?node-id=4%3A2903

**Comment by damianr** [comment]
These look great @bellebellesol
