### ISSUE TITLE
Add a link to home (logo?) in sticky Listings div

### ISSUE THREAD

**Issue by sjc5** [holaplex/holaplex#180]
## Problem:

No way to easily get back to home / top when you are near the bottom of the infinite scroll listings

## Potential Solution:

Add a link to home (maybe that calls `scrollToTop`) in the sticky Current Listings div

cc @damianr @bellebellesol

**Comment by damianr** [comment]
Sounds good

**Comment by GoOsTT** [comment]
Hey, 

I'd love to work on this, could you asssing this to me? 
Thanks,

_M

**Comment by sjc5** [comment]
> 

Hi there @GoOsTT, we would love to have you help out with this issue.  I will assign it to you, and don't hesitate to reach out if you have any questions or run into any problems

**Comment by sjc5** [comment]
Hey there @Acjenkins6440 -- We actually already deployed a similar fix, where clicking on "Current Listings" auto-scrolls to the top of the NFT discovery section.  I am going to close this, but we would absolutely love if you found some other issue to help out (or even propose one!).  Thanks again @Acjenkins6440
