### ISSUE TITLE
Error: Cannot find module '@/modules/db'

### ISSUE THREAD

**Issue by rusty-h1000** [holaplex/holaplex#230]
while following the README.md, I ran `SOLANA_PUBKEY=${SOLANA_PUBKEY} yarn run db:seed` I am getting this `Error: Cannot find module '@/modules/db' 

I tried yarn add -D node-modules modules  but I guess it's not what the error meant me to do.. plz help!

![D-shot-Fullscreen_2022-02-23-155921](https://user-images.githubusercontent.com/98808554/155301910-f686256e-d471-405b-80ab-9e4f53f4916c.png)

**Comment by kespinola** [comment]
Appreciate the report. The seed file is from the earliest version of Holaplex and is no longer a required step in developing. 

We will remove it shortly for now if you have the db running and migrations ran than you are ready to go.

**Comment by kespinola** [comment]
The specific error if you want to address is the use of `@/` alias. The aliases are only set up for the next server and any scripts being run need to use relative path references ie ../../src/modules/*

**Comment by parallax3030** [comment]
Thanks both! I changed the imports per Kyle's suggestion, then got another error about Typescript not compiling so I changed the index.ts to this and I was able to run the seed

![image](https://user-images.githubusercontent.com/57077614/155447832-a58fbb9e-c7cf-45b7-ac8c-ac08bc7c6dea.png)
