### ISSUE TITLE
Profiles - General

### ISSUE THREAD

**Issue by bellebellesol** [holaplex/holaplex#242]
**Sticky pfp section on scroll**

- [x] If possible, for desktop only, make the pfp section sticky on scroll when it reaches the position of 40px below the navigation bar 

**Overall**

- [x] Remove the toast that appears when clicking the copy icon beside pubkey and instead replace copy icon with white 'check' icon used in toast. Show check icon for 2 seconds then switch back to copy icon

<img width="496" alt="Screen Shot 2022-02-28 at 4 37 08 pm" src="https://user-images.githubusercontent.com/95664179/156013423-64ac7644-2f94-4b34-af9e-9bb91b209e0c.png">

- [x] On desktop screen sizes, change profile banner image height to 16rem (if it is not this size already) 

- [x] On mobile screen sizes, change profile banner image height to 10rem

 Currently looks like:
 
<img width="335" alt="Screen Shot 2022-03-15 at 12 06 57 pm" src="https://user-images.githubusercontent.com/95664179/158374424-1fa8dbd4-4167-4ae1-99ff-7dc1ce39c4fc.png">

 Should look like:
<img width="498" alt="Screen Shot 2022-03-15 at 12 06 00 pm" src="https://user-images.githubusercontent.com/95664179/158374315-374e0c04-c9f2-4991-8fe8-4f2d3324a502.png">

- [x] On desktop screen sizes, make activity images 80pxX80px 

- [x] If connected and viewing own profile, make 'You' and SOL amounts Grey 300. Only pubkeys, NFT names and store names should be white and all should link to profiles / storefronts accordingly 

- [x] In all activity events, show the square image of the NFT or listing that was interacted with instead of the round pfp of a wallet (except for follow events) 

- [x] Activity tab empty state container should be the same width as the tabs bar 

- [x] Add local search to activity 

Currently looks like:
<img width="931" alt="Screen Shot 2022-03-04 at 3 57 37 pm" src="https://user-images.githubusercontent.com/95664179/156816658-deea7799-9ed8-4761-bcbd-8ef17efbaa1f.png">

Should look like:
<img width="696" alt="Screen Shot 2022-03-04 at 4 00 43 pm" src="https://user-images.githubusercontent.com/95664179/156816686-551ff83d-8682-4194-bfa8-0cc61f9d1d5d.png">

**Comment by shreyjay0** [comment]
While setting up the associated branch to work on this, I ran into an error due to this local path dependency in package.json "@holaplex/graph-program": "file:../graph-program/sdk/". I can't find the package in any repo. Where can I find it?

**Comment by kristianeboe** [comment]
> While setting up the associated branch to work on this, I ran into an error due to this local path dependency in package.json "@holaplex/graph-program": "file:../graph-program/sdk/". I can't find the package in any repo. Where can I find it?

Hi there. Which branch where you trying to develop on? If you start from "dev" you should be fine. The graph program is a new addition that has not been fully merged in yet.

I saw you fixed another ticket for us the other day. If you want to be more involved feel free to contact me as @kristianeboe on Discord and we can have a chat :)

**Comment by bellebellesol** [comment]
Edit: removed task for sticky header navigation on scroll after decision was made not to do this elsewhere (eg. global search) @damianr
