### ISSUE TITLE
Owned NFTs

### ISSUE THREAD

**Issue by bellebellesol** [holaplex/holaplex#243]
- [x] Search bar should be full width (less 1rem space between the end of it and display switcher on the right) 

- [x] Change placeholder text and search icon to Grey 500 

Currently it looks like:
<img width="931" alt="Screen Shot 2022-03-01 at 6 37 04 pm" src="https://user-images.githubusercontent.com/95664179/156219782-012c7941-7eab-43d1-a1c7-be0f1aba5c73.png">

Should look like: 
<img width="771" alt="Screen Shot 2022-03-01 at 5 03 42 pm" src="https://user-images.githubusercontent.com/95664179/156204125-076b777b-197e-4d39-97aa-146bf37bba43.png">

Design for reference: https://www.figma.com/file/DC1T92jSoSIw9rvvEJytNK/Profiles---MVP?node-id=4347%3A9293

- [x] Truncate long NFT names / creator names in the same way we handle this for listing cards on discovery. Currently looks like: 

<img width="593" alt="Screen Shot 2022-03-07 at 2 43 39 pm" src="https://user-images.githubusercontent.com/95664179/157048485-0c590698-8dd4-4f50-aa1b-b94f08cfea63.png">

Should look like:  
<img width="308" alt="Screen Shot 2022-03-07 at 2 58 27 pm" src="https://user-images.githubusercontent.com/95664179/157048542-a15e3f04-fdad-4f54-9b29-ae129edd6907.png">
<img width="319" alt="Screen Shot 2022-03-07 at 2 58 03 pm" src="https://user-images.githubusercontent.com/95664179/157048558-fa9ef48a-de83-42c7-8de8-91595bc27fdd.png">

**Comment by shreyjay0** [comment]
Hi, Can i work on this?

**Comment by dandlezzz** [comment]
@shreyjay0 please! Feel free to ask any questions here too!

**Comment by davetorbeck** [comment]
Hi @shreyjay0.  If you do decide to work on it, please open a PR against this branch: https://github.com/holaplex/holaplex/tree/nft-collection

Should only be a few tailwind classnames that need to be changed :)

**Comment by shreyjay0** [comment]
Ok thanks, I'll do that

**Comment by bellebellesol** [comment]
@kristianeboe 

- make creator wallet addresses on owned nft cards the space mono typeface we use elsewhere in profiles
currently looks like:
<img width="115" alt="Screen Shot 2022-03-22 at 9 24 21 pm" src="https://user-images.githubusercontent.com/95664179/159578627-c34e9170-a246-4098-b3e3-eee1872a2e8b.png">
should look like:
<img width="252" alt="Screen Shot 2022-03-22 at 9 24 01 pm" src="https://user-images.githubusercontent.com/95664179/159578652-c2f77ebf-5b90-4479-ad97-0fdbcaeb18b5.png">


- local search icon should be grey-500 until field is in focus and icon changes to white. there should also be 16px padding left of search icon
currently looks like:
![image](https://user-images.githubusercontent.com/95664179/159578354-69fa54a5-3075-4276-be4d-3d103e78ccbf.png)
should look like:
![image](https://user-images.githubusercontent.com/95664179/159578382-e086fba0-ba77-487a-9e36-9f33f6929cef.png)

**Comment by bellebellesol** [comment]
- [ ] Change the name of 'Owned' tab to 'Collected'
