### ISSUE TITLE
How to set auction with an own splt token ?

### ISSUE THREAD

**Issue by SolSecSociety** [holaplex/holaplex#270]
Hi all, i've deployed my store but i can't find out to change the auction tocken (which is SOL by default) into my own token.

How can i manage that ? Is this possible ?
Thanks

**Comment by kristianeboe** [comment]
We will not support other SPL tokens in our storefront product unfortunately, but if you think your project can fit into our new Marketplace product (ex: https://junglecats.holaplex.market/) we will soon release "Other SPL token support" for that. Please get in touch if that's the case :)
