### ISSUE TITLE
NFT details cleanup

### ISSUE THREAD

**Issue by bellebellesol** [holaplex/holaplex#284]
Design QA pointers/measurement pics: https://www.figma.com/file/MxzeTx3eaLDISbxRBuI9JU/Miscellaneous?node-id=212%3A12421
NFT Detail design file: https://www.figma.com/file/snKvxHcJI50oFduGsVvsoi/?node-id=0%3A1

- [x] Hide attributes accordion completely if NFT has no attributes

- [ ] For aspect ratios 1:1, 3:2, 5:4 use this standard layout - but for wider aspect ratios like  4:3, 16:9, wrap the NFT detail elements and set to full width so that image is centred and optimized. Example:
<img width="567" alt="Screen Shot 2022-04-01 at 1 44 46 pm" src="https://user-images.githubusercontent.com/95664179/161268516-5accc918-5088-4e28-bafb-76d04f2a9874.png">
[Design here](https://www.figma.com/file/MxzeTx3eaLDISbxRBuI9JU/Miscellaneous?node-id=212%3A12421)

- [x] Created by / Owned by labels should be Grey-300
Currently looks like:
<img width="298" alt="Screen Shot 2022-04-01 at 12 36 00 pm" src="https://user-images.githubusercontent.com/95664179/161255877-ecc29f6c-4370-4cc9-9a45-ad0a32dffb5a.png">
Should look like:
<img width="307" alt="Screen Shot 2022-04-01 at 12 36 05 pm" src="https://user-images.githubusercontent.com/95664179/161255875-1f596580-3ead-4b89-b819-0a88fa06e611.png">

- [x] Owned by elements should be right aligned 
Currently looks like:
<img width="551" alt="Screen Shot 2022-04-01 at 12 44 06 pm" src="https://user-images.githubusercontent.com/95664179/161257117-4a2e0354-4ce2-4e3a-becb-cc77bcbf5b60.png">
Should look like:
<img width="581" alt="Screen Shot 2022-04-01 at 12 44 27 pm" src="https://user-images.githubusercontent.com/95664179/161257114-95d1faf3-c906-4b0d-be01-555755209ddf.png">

- [x] NFT name should be font size 24px / line height 32px / weight semibold
Currently looks like:
<img width="254" alt="Screen Shot 2022-04-01 at 12 35 14 pm" src="https://user-images.githubusercontent.com/95664179/161255780-99d86427-16bb-4c6c-956c-b88b07bb22a6.png">
Should look like:
<img width="151" alt="Screen Shot 2022-04-01 at 12 35 19 pm" src="https://user-images.githubusercontent.com/95664179/161255776-6ab241e2-3a8e-47fb-b965-595c043bb5a9.png">

- [x] Anywhere there is a wallet address instead of a twitter handle (including creators in cards in owned tab) use space mono font being used elsewhere
Currently looks like:
<img width="112" alt="Screen Shot 2022-04-01 at 1 11 34 pm" src="https://user-images.githubusercontent.com/95664179/161260888-768127db-642f-4e8a-bddb-6d5660f333f4.png">
Should look like:
<img width="212" alt="Screen Shot 2022-04-01 at 1 12 10 pm" src="https://user-images.githubusercontent.com/95664179/161260884-0831be5e-9989-49a7-b4e3-830dd53d1b27.png">

- [ ] Actions dropdown button should have a dropshadow so it appears to be floating (and keep dropshadow when button active) - some of these points are easier to see/compare in figma, have a look at the [screenshot and design side by side for reference](https://www.figma.com/file/MxzeTx3eaLDISbxRBuI9JU/Miscellaneous?node-id=212%3A12421)
Currently looks like:
<img width="67" alt="Screen Shot 2022-04-01 at 12 36 36 pm" src="https://user-images.githubusercontent.com/95664179/161256087-487a5abd-f5a3-4bbe-ab70-b649faa7675f.png">
Should look like:
<img width="67" alt="Screen Shot 2022-04-01 at 12 36 41 pm" src="https://user-images.githubusercontent.com/95664179/161256085-2b0575ec-7316-4313-8979-1fa386a4ba98.png">

**Dropdown menu**
- [x]  Bg color should be Grey-900
- [x] Dropdown should have 8px border radius
- [x] Icons should be 16px by 16px (usually it's 24px but 16px looks best here)
- [x] Dropdown should align with the right side of the icon button above it
Currently looks like:
<img width="297" alt="Screen Shot 2022-04-01 at 2 04 05 pm" src="https://user-images.githubusercontent.com/95664179/161269529-2daf405c-3cd5-433f-8af1-8e0ec67e8dd9.png">
Should look like:
<img width="196" alt="Screen Shot 2022-04-01 at 2 20 25 pm" src="https://user-images.githubusercontent.com/95664179/161271777-3dcc07e9-8dc6-4c6c-b664-b8bbfe67b74e.png">
<img width="462" alt="Screen Shot 2022-04-01 at 2 17 19 pm" src="https://user-images.githubusercontent.com/95664179/161271238-7543d72b-29cc-418f-973a-74bc19e3ec4e.png">

- [x] All borders/dividers should be Grey-800 and have border radius 8px (accordions, attribute containers, dividers etc)
Currently looks like:
<img width="529" alt="Screen Shot 2022-04-01 at 12 38 32 pm" src="https://user-images.githubusercontent.com/95664179/161256281-89e39140-f191-4808-88a1-efa4d7f9465d.png">
<img width="606" alt="Screen Shot 2022-04-01 at 1 23 27 pm" src="https://user-images.githubusercontent.com/95664179/161262996-d20f6bef-a284-467c-80da-a757504ee2a4.png">
Should look like:
<img width="570" alt="Screen Shot 2022-04-01 at 12 38 25 pm" src="https://user-images.githubusercontent.com/95664179/161256285-3cc58aab-c2a1-497b-98f5-bbd43461d201.png">
<img width="669" alt="Screen Shot 2022-04-01 at 2 32 06 pm" src="https://user-images.githubusercontent.com/95664179/161273639-fae3f3ae-c6c1-45cc-b0a8-64eb0d43e101.png">

**Attributes containers**

**Comment by bellebellesol** [comment]
**Attributes**
 
  - [ ] Should be 16px padding inside the expanded accordion 
  - [ ] Should be 16px inside each individual attribute container, and 16px vertical + horizontal spacing between each attrib container 
  - [ ] Change attrib labels to just first letter capitalized, not full caps 
  - [ ] Change attrib labels to font size 16px / line height 24px / weight medium 
  - [ ] Attrib labels should be Grey-300 
  
  Currently looks like: 
  <img width="647" alt="Screen Shot 2022-04-01 at 1 07 30 pm" src="https://user-images.githubusercontent.com/95664179/161275549-0978e0f5-d6eb-433a-818d-37271a76a1c0.png"> 
  
  Should look like:
   <img width="400" alt="Screen Shot 2022-04-01 at 2 43 40 pm" src="https://user-images.githubusercontent.com/95664179/161275718-796a45d2-4792-4002-a11f-c3bd3524467d.png"> <img width="581" alt="Screen Shot 2022-04-01 at 2 39 39 pm" src="https://user-images.githubusercontent.com/95664179/161275772-320db012-b3dc-4918-8dde-4610ed0c6394.png"> <img width="606" alt="Screen Shot 2022-04-01 at 2 39 20 pm" src="https://user-images.githubusercontent.com/95664179/161275779-eca2765a-ed34-4efd-a21e-b678a4aa3394.png">

**Comment by bellebellesol** [comment]
- [ ] 80px on left and right of page content, 40px between NFT image and details columns in standard layout

**Comment by bellebellesol** [comment]
- [ ] Change all 'Owned by' labels to 'Collected by' at the same time as the 'owned' tab in profiles gets changed to 'Collected'

**Comment by bellebellesol** [comment]
- [ ] Make sure to use 'Listed by' when the NFT is listed for sale instead of 'Collected by' - unlisted only

**Comment by bellebellesol** [comment]
**Offer flow cleanup** 

- [ ] Fix container height/padding - should be 24px padding all the way around

Currently looks like:
<img width="645" alt="Screen Shot 2022-04-07 at 4 09 46 pm" src="https://user-images.githubusercontent.com/95664179/162238528-7ecdefd6-e653-4995-bf79-1eb1a0ae1071.png">

Should look like:
<img width="623" alt="Screen Shot 2022-04-07 at 4 40 31 pm" src="https://user-images.githubusercontent.com/95664179/162238689-0248b160-3150-441f-8152-9b8af0bcfe1b.png">


- [ ] modal should hug contents vertically, looking like a bit too much space under the button. 
- [ ] disable the primary button in all modals until a valid amount is entered into the field or while there is an invalid amount entered. show 'Please enter a valid amount' error message while invalid amount is entered but remove if amount gets deleted.
- [ ] only show error message for invalid amount entered if 
- [ ] disable alphabetic entries in pricing fields and remove 'must be a number' error message


Currently looks like:
<img width="640" alt="Screen Shot 2022-04-07 at 4 40 57 pm" src="https://user-images.githubusercontent.com/95664179/162239232-27047753-06aa-4539-89ad-bd2d2655ba7a.png">
<img width="223" alt="Screen Shot 2022-04-07 at 6 03 47 pm" src="https://user-images.githubusercontent.com/95664179/162258125-186d2e70-fa48-41e9-8754-08d554576397.png">
<img width="499" alt="Screen Shot 2022-04-07 at 6 05 52 pm" src="https://user-images.githubusercontent.com/95664179/162258411-9ffcb11e-5c50-4e24-ac7d-7527d36f04ca.png">
<img width="234" alt="Screen Shot 2022-04-07 at 6 05 28 pm" src="https://user-images.githubusercontent.com/95664179/162258424-8e87bd91-315a-4520-90d1-97fc98c0ef7e.png">


Should look like:
<img width="270" alt="Screen Shot 2022-04-07 at 4 41 48 pm" src="https://user-images.githubusercontent.com/95664179/162239352-5378f3a8-98c0-4809-8ae4-d3e17ef5ba4b.png">


- [ ] 
Currently looks like:
Should look like:

**Comment by kespinola** [comment]
> while waiting for transaction signature to be approved by user and when transaction is confirming, just show the load spinner in buttons (same as when you follow a profile)
Currently looks like:

@bellebellesol this one may be slightly annoying to implement everywhere. In most cases we set button width to the container which works for this but that isn't always the case. The text is what defined the width if we remove that then nothing to take the space. Can may do with text opacity 0 and spinner position absolute. Dev working on this approach with a little caution.

**Comment by damianr** [comment]
We should think through this a bit if we're looking to solve this problem globally in all our apps. I followed a bunch of people yesterday and TPS was bad so it took a long time. I didn't realize that it wasn't done and canceled out a few by leaving the page. We should look at doing a modal that makes it super clear that important stuff is happening to prevent users from leaving. ME does this well when you list or buy an NFT. @bellebellesol thoughts?

**Comment by damianr** [comment]
Also we should make sure it;'s clear what items on this list if any are blockers for release. We're trying to move fast and might need to tackle some of this after launch.

**Comment by bellebellesol** [comment]
a loader modal should work if you're hitting follow on the profile but i don't like the thought of being in the followers/following modal, hitting follow on someone in the list and getting another modal or popup. have to revisit this one. i think we also need to cull some toasts - we have so many that pop up with every action.
