### ISSUE TITLE
Make an Offer on NFT

### ISSUE THREAD

**Issue by kespinola** [holaplex/holaplex#294]
![Screen Shot 2022-04-04 at 12 33 23 PM](https://user-images.githubusercontent.com/2388118/161618429-c781cd21-80dc-49d9-9697-be561973c0c6.png)

```
/nfts/{address}/offers/new
```

```
query {
market(subdomain: "holaplex") {
  auctionHouse {
    ...
  }
}

nft(address: "") {
  offers {
    ...
  }
}
}
```

### References

https://github.com/holaplex/marketplace/blob/dev/src/pages/nfts/%5Baddress%5D.tsx#L706

https://github.com/holaplex/marketplace/blob/dev/src/components/Offer/index.tsx#L47

**Comment by bellebellesol** [comment]
Design - making an offer on unlisted NFT: https://www.figma.com/proto/snKvxHcJI50oFduGsVvsoi/NFT-Details?node-id=0%3A1&viewport=261%2C48%2C0.05&scaling=scale-down&starting-point-node-id=1%3A3466&show-proto-sidebar=1

Design - making an offer on listed NFT: https://www.figma.com/proto/snKvxHcJI50oFduGsVvsoi/NFT-Details?node-id=0%3A1&viewport=261%2C48%2C0.05&scaling=scale-down&starting-point-node-id=11%3A5386&show-proto-sidebar=1
