### ISSUE TITLE
A created tab in Profiles

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#305]
- [x] Get the created query in the frontend
```
query {
  nfts(creators: ["4QawWnjkTW91g3Qvh3cz39C9xQ4VQB6s181XB6xAe6hY"], limit: 10, offset: 0) {
    image
  }
}
```
- [x] Add a new tab next to owned called created
- [x]  Change owned to collected

**Comment by bellebellesol** [comment]
Design: https://www.figma.com/file/DC1T92jSoSIw9rvvEJytNK/?node-id=5056%3A12494
