### ISSUE TITLE
Update Offer on NFT

### ISSUE THREAD

**Issue by milorue** [holaplex/holaplex#311]
![image](https://user-images.githubusercontent.com/3159469/161834842-d7d7208e-49fe-4833-83d8-0b86724a7f2c.png)

- [x] Cancel Offer
- [ ] Update Offer

**Comment by bellebellesol** [comment]
Putting these links here for visibility  

Figma prototype - making an offer on unlisted NFT: https://www.figma.com/proto/snKvxHcJI50oFduGsVvsoi/NFT-Details?node-id=0%3A1&viewport=261%2C48%2C0.05&scaling=scale-down&starting-point-node-id=1%3A3466&show-proto-sidebar=1

Figma prototype - making an offer on listed NFT: https://www.figma.com/proto/snKvxHcJI50oFduGsVvsoi/NFT-Details?node-id=0%3A1&viewport=261%2C48%2C0.05&scaling=scale-down&starting-point-node-id=11%3A5386&show-proto-sidebar=1

Figma file - includes mobile design: https://www.figma.com/file/snKvxHcJI50oFduGsVvsoi/?node-id=0%3A1
