### ISSUE TITLE
Multi-transaction Actions

### ISSUE THREAD

**Issue by milorue** [holaplex/holaplex#317]
For multi-transaction actions like Update Listing | Update Offer | Accept Offer/Cancel Listing we need to establish a standardized flow on how the user can resolve these.

A possible solution could be a component that can take in (N) amount of Transactions and at each step after an initial step there would be a modal that prompts the user to approve another transaction and reflects the status in a loading bar of some sorts (bottom screen or something)

**Comment by damianr** [comment]
@milorue how much info will we have access to for each step? Can we count on a readable title or description for the action? like "Cancel offer" -> "Create new offer"

**Comment by milorue** [comment]
Yes we should know what the transactions are doing and can therefore attach metadata about said request to the component

> @milorue how much info will we have access to for each step? Can we count on a readable title or description for the action? like "Cancel offer" -> "Create new offer"
