### ISSUE TITLE
Offer/sell on profile QA

### ISSUE THREAD

**Issue by damianr** [holaplex/holaplex#329]

**Comment by damianr** [comment]
### High priority
Offers section should be expanded if there are offers. @bellebellesol this is another place where we need to show count. Let's figure out a global solution to this. Also when collapsed there should be rounded corners on the bottom.
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/260165/163470823-e325b967-39af-4b14-935e-ed2dccfbbde8.png">


### Lower priority
Need Empty state for Collected and Created tabs
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/260165/163470610-96de4bf7-33cf-4859-a3ad-5d0eaa63a402.png">


Way too much padding for the attributes section plus the borders on the side don't connect
<img width="763" alt="image" src="https://user-images.githubusercontent.com/260165/163470975-213b3dfc-6d5a-428c-a402-a1137b454ac1.png">

**Comment by milorue** [comment]
Yes the padding issue is a grid issue with the parent element easy enough fix

**Comment by damianr** [comment]
- Hide floor and avg price if we don't have data
- Use nifty new transaction modal here:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/260165/163490050-12de19d0-f024-48e5-a6ff-e75528021d33.png">
