### ISSUE TITLE
Add auction house activity items to the activity page

### ISSUE THREAD

**Issue by damianr** [holaplex/holaplex#335]
Add events on activity page when a wallet does any of the following on a profile or marketplace:
- Buys an NFT
- Lists an NFT
- Cancels listing
- Makes an offer on an NFT
- Accepts offer for an NFT

These items should link to the nft details page.

**Comment by kristianeboe** [comment]
Also, make sure the activity tab is visible on big screens


![Image](https://user-images.githubusercontent.com/10433154/180179453-da86eb2b-03cc-4a85-8023-bf9d7f7c3056.png)
