### ISSUE TITLE
Shareable nft details page

### ISSUE THREAD

**Issue by milorue** [holaplex/holaplex#340]
Sharing an nft details page should provide the metadata around last sale, is listed, has offers, list price, etc.

**Comment by damianr** [comment]
**Goal**
- When NFT details page is shared on twitter we use the appropriate meta tags to make the image and name of the NFT look good
- Add a clear share CTA to the NFT details page even if this just copies the URL to the NFT to clipboard and makes that clear
- Add share CTA to the last step of listing, making an offer, and buying flows

**Design needed**
- [ ] Sharing "offramp" for actions on NFT
- [ ] Share CTA on NFT details page
