### ISSUE TITLE
Trending NFTs Section | Home

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#344]
![image](https://user-images.githubusercontent.com/10433154/164012118-616640e6-a2d3-4c51-8b82-ff8972d56342.png)

We need a "What's hot" section to highlight NFTs that have a high number of / recent offers / high price

- [ ] graphql query for fetching NFTs sorted by offer size, frequency and # 
- [ ] Updated / New NFT preview card
- [ ] The Section/ Grid component laying out the NFTs and linking to /discover/activeoffers

**Comment by austinmilt** [comment]
My Notes

## What’s Hot

NFTs listed as Buy Now in auctionhouses

### Data

- list of “Hot” NFTs (as NFT address pubkeys)
- For each NFT (see [[marketplace](https://github.com/holaplex/marketplace/blob/dev/src/components/NftCard/NftCard.tsx)](https://github.com/holaplex/marketplace/blob/dev/src/components/NftCard/NftCard.tsx) repo), just use the [[card from profiles](https://github.com/holaplex/holaplex/blob/dev/pages/profiles/%5BpublicKey%5D/nfts.tsx#L67)](https://github.com/holaplex/holaplex/blob/dev/pages/profiles/%5BpublicKey%5D/nfts.tsx#L67)
    - image URL (`image` from gql `nft` query with NFT address as `address`)
    - num offers (`offers` list from gql `nft` query with NFT address as `address`)
    - creator/seller (badge address)
    - price in SOL (`price` in `listings` from gql `nft` query with NFT address as `address`)
    - Buy Now info (from NFT address pubkey)
    - NFT holaplex page address (from NFT address pubkey)

### Unmet Data Needs

- list of “Hot” NFTs (as NFT address pubkeys), with limit
    - weighting (roughly in order of importance)
        - number of offers (relative to time the listing has been up)
        - listed from high-ranked profile (ranking algorithm tbd)
        - historical price
        - previous sales
    
    ** Ranking criteria can be weighted or waterfall (only rank on next criterion if two options are equal)

**Comment by austinmilt** [comment]
Meeting Notes
- ideally we would first select high-ranked profiles, and secondarily rank by number of offers, etc
- Kyle will talk to indexer folks to see about: every time we index a connection, will have total followed and following count, kept up to date so we can easily join to other attributes (total volume sold, total collected, etc) (`walletTotals`)
- longer term: rank profiles by more than followers/following
- can adapt listings root query with optional params of `auctionhouses`, `creators`

**Comment by austinmilt** [comment]
@kespinola the Graph QL queries would look something like

```graphql
query FeaturedBuyNowListingsQuery($limit: Int = 10, $offset: Int = 0) {
  listings($limit, $offset) {
    address
    nfts {...}
  }
}

```

**We need to be able to link NFTs to marketplaces to meet reqs. Do we have the ability to do that, such that, as part of this, we can add `marketplace` to the `nft` schema (or alternatively the `listings` schema)?**

The meeting notes mention to include optional `auctionhouses` and `creators` parameters, but I dont understand where those would come into play, so just making another note here.

**Comment by kristianeboe** [comment]
Initial algorithm: Sort by highest amount of offers
secondary(in next release): how "popular" is the creator
