### ISSUE TITLE
New Hero Section | Home

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#345]
![image](https://user-images.githubusercontent.com/10433154/164030323-73e534c6-d71e-4f7f-89b2-09c7d573c5f6.png)

- [ ] style hero section and content
~~- [ ] figure out how to approximate # of NFTs on the Solana blockchain~~
- [ ] get and display some featured NFTs

**Comment by kristianeboe** [comment]
The hero text content might change

**Comment by austinmilt** [comment]
My notes RE new Hero Section

## Hero Section

### Data

- number of NFTs indexed
- list of recently minted NFTs (as NFT address pubkey)
    - image URL (gql `nft` query)
    - creator list (pubkey) (gql `nft` query)
    - store page URL (gql `nft` query)

### Unmet Data Needs

- gql endpoint for total number of NFTs indexed
    - start with the current count, then
    - roughly how many NFTs are minted per minute on solana, and tally based on that... rather than get a true count
- gql endpoint for list of hero NFTs (as NFT address pubkeys), with limit
    - specific ranking attributes TBD with meeting with Kyle
        - show me highest ranked profiles that are 1-of-1 creators
    - weightings based on
        - recently minted 1-of-1 (non candy machine)
        - high ranked profile
        - number offers

**Comment by austinmilt** [comment]
Meeting notes:
- doing a point-in-time count of all minted NFTs times out (there are too many)
- we can get a rough idea of how many NFTs are minted in some time period: query mint events by some time range in total count
- ranking profiles by num followers will be slow/difficult to join to newly minted NFTs
- **start with only taking NFTs minted in last 24 hours, and only rank those creator profiles by number of followers**
- if possible, filter out candy-machine mints

**Comment by austinmilt** [comment]
@kespinola the Graph QL queries would look something like

### Featured NFTs
```graphql
query FeaturedNftsQuery($limit: Int = 10, $offset: Int = 0){
  featured_nfts(limit: $limit, offset: $offset) {
    nfts(...)
  }
}
```

where `nfts(...)` is the schema for NFTs.

I dont think the endpoint should expose the time range as a parameter, since it is part of the black box "featured NFTs" ranking algorithm.

### Number of NFTs Indexed
```graphql
query () {
  mint_rate() {
    total
  }
}
```

**Comment by kristianeboe** [comment]
query "discovery" feed

- [ ] need to create a featured follow wallet
- [ ] show 4 latest creation events
