### ISSUE TITLE
New Navbar | Home

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#346]
until we release the full discover page, we won't be able to link to listings or profiles in the discover dropdown seen in initial designs. here are designs for the nav bar we will use up until we have discover page:
*note that the 'create' link is simply rewording the 'mint nfts' link

not connected
<img width="726" alt="Screen Shot 2022-05-17 at 6 14 02 pm" src="https://user-images.githubusercontent.com/95664179/168872139-2b55fccf-7d57-49ad-a76c-c1ed78dc4787.png">

connected
<img width="723" alt="Screen Shot 2022-05-17 at 6 14 07 pm" src="https://user-images.githubusercontent.com/95664179/168872150-f99291db-dc1a-44f0-8cde-13f9eb8d893b.png">

figma link: https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=1660%3A10255

- [x] integrate with global search
- [ ] connected profile popover menu

**Comment by kristianeboe** [comment]
![image](https://user-images.githubusercontent.com/10433154/168665318-4266d0a3-7bb7-40f7-908c-c18a5e5638f7.png)
Make it transparent

**Comment by kristianeboe** [comment]
and fixed

**Comment by bellebellesol** [comment]
- [ ] give notification button and pfp button a darker drop shadow
- [ ] use filled notification icon
<img width="242" alt="Screen Shot 2022-05-17 at 2 01 06 pm" src="https://user-images.githubusercontent.com/95664179/168818234-3da6b0ac-7da0-43af-8e64-427caac1eb9f.png">

- [ ] tweak the unread notification state so it looks like this
<img width="256" alt="Screen Shot 2022-05-17 at 2 01 16 pm" src="https://user-images.githubusercontent.com/95664179/168818416-13b89cdb-7813-4e25-8479-0bbd8c673773.png">

- [ ] when notification button active use the white active state 
<img width="311" alt="Screen Shot 2022-05-17 at 2 01 28 pm" src="https://user-images.githubusercontent.com/95664179/168818197-951f8e49-c7fa-486d-9a2a-d553b8e62b83.png">

**Comment by bellebellesol** [comment]
> and fixed

@damianr i thought we decided against the sticky nav bar? will clash with the sticky filter buttons/local search in profiles that milo added recently and might present weird states when interacting with global search while scrolled down the page.
