### ISSUE TITLE
Profiles to Follow section | Home | Feed

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#347]
![image](https://user-images.githubusercontent.com/10433154/164031406-b92b4e5c-7471-41f0-98ae-28b7092b17b6.png)

# Frontend
- [ ] create the DiscoverProfileCard
- [ ] create a component for the DiscoverProfileSection (or similar)
- [ ] get featured profiles into the page either through graphql (speced below) 
    * Rejected: or by curating a big list (50+) of influential profiles and simply pick a random subset of them to show (- anyone they have already followed if the user is connected)

# Backend
Will power
* Who to follow on Home page
* Who to follow on Feed

We need a graphql endpoint to fetch this datastructure(more or less)
topProfiles(address?, list/criterias?) {
users: {
      followerCount
      followingCount
      collectedCount (nfts)
      createdCount(nfts)
      user: { 
         address
         profile: {
             handle
         }
     }[]
}

## sorting criteria (ideas)
* followerCount
* collectedCount
* createdCount // weighted or logarithmic 
* offersCount
* volumeOfSolBoughtFor
* volumeOfSolSoldFor

We need to determine how easy/hard these attributes are to collect
In the end we will have 3 lists, each with different weights/combination of sorting criteria
* All
* collectors
* creators

## Steps
1. non contextual, only based on follower count
2. non contextual, sorting based on multiple attributes
3. contextual, based on who you follow

**Comment by bellebellesol** [comment]
Figma: https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=355%3A11223

**Comment by kespinola** [comment]
Our existing wallet object if fairly close to fulfilling this views requirements. Need to add nftCounts#created

```
query {
  wallet(address:"CqC5dNspaUVbUz6QDbNcodpTfgbw1nZ4ra2nectDv1ak") {
    nftCounts {
      listed
      owned
      offered
    }
    connectionCounts {
      fromCount
      toCount
    }
  }
}
```

Like to use that object but return from a follower specific root query like 

```
followWallets(wallet: PublicKey, limit: Int!, offset: Int!): [Wallet!]!
```

MVP make this return wallets with the most followers that the wallet does not already follow. The wallet parameter is optional to power "who to follow" when no wallet is connected.

**Comment by kristianeboe** [comment]
@kespinola sounds good!

**Comment by kristianeboe** [comment]
@austinmilt We will start off with a hard coded list of address, handle, pfp and banners, so we can hide the collected and created label pr card for now

**Comment by austinmilt** [comment]
@kristianeboe The query has already been merged to `indexer`... just needs to go to prod for the frontend to be ready

**Comment by austinmilt** [comment]
> @austinmilt We will start off with a hard coded list of address, handle, pfp and banners, so we can hide the collected and created label pr card for now

I can hard-code a list of profile pubkeys and still use the profile preview query to collect all the relevant info
