### ISSUE TITLE
New trending auctions section | Home

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#349]
![image](https://user-images.githubusercontent.com/10433154/164034251-bc82cc80-e654-4d02-a1af-1094d091bb01.png)

- [ ]  Repurpose existing listing card into this grid
- [ ] move away from REST endpoint to power listing discovery and over to graphql
- [ ] update ListingPreveiw component if nececary

**Comment by austinmilt** [comment]
My Notes

## Trending Auctions

### Data

- list of trending auction NFTs (as NFT address pubkey)
- For each trending auction
    - NFT name
    - current bid
    - end date

### Unmet Data Needs

- gql endpoint for list of trending auction NFTs (as NFT address pubkey), with limit
    - display same info as trending auctions in current homepage
- current bid and end date in `nft` gql endpoint... or address query variable for `listings` endpoint
