### ISSUE TITLE
Expose Mint Address on /nfts/:address page

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/holaplex#363]
We need to expose the mint_address on the nft details page.

**Comment by bellebellesol** [comment]
- [ ] Remove links to solscan and explorer from the actions dropdown

- [ ] Add a new 'Details' accordion below Attributes with mint address, token address, creator royalties and transaction fee info. Link to solscan and explorer beside mint and token address.
<img width="426" alt="Screen Shot 2022-04-25 at 12 48 54 pm" src="https://user-images.githubusercontent.com/95664179/165083193-323fd677-62ba-469b-9221-0d60d00de1b5.png">

Figma: https://www.figma.com/file/snKvxHcJI50oFduGsVvsoi/NFT-Details?node-id=447%3A8659
