### ISSUE TITLE
Missing Click Handler on Offers tab

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/holaplex#378]
On the profile Offer's tab, I can't click the NFT image that is the subject of the offer.

I can click the title of the NFT, but the image should click too!
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/5935947/165140401-13289c64-a7a9-4d52-bb5d-efa7079252f4.png">

**Comment by kristianeboe** [comment]
Fixed
