### ISSUE TITLE
Profiles -- Purchased NFT not showing in wallet

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#385]
Alex Kefaya profile tried to purchase two separate NFTs.

<img width="322" alt="Screen Shot 2022-04-25 at 2 30 38 PM" src="https://user-images.githubusercontent.com/98030332/165195826-3bcdc936-d4f3-45a8-b785-3bccb380cad6.png">

<img width="788" alt="Screen Shot 2022-04-25 at 2 25 25 PM" src="https://user-images.githubusercontent.com/98030332/165195824-40b516f0-6d2d-4b27-ab5f-ac06e6a43301.png">

Transactions -- 

https://solscan.io/tx/3QfowBYEnKok41NfHPkcV1zHc7edc1yTmecMFAmuxU4qgPbSifwcg6uszdf99aZsoFnVYmXEwjRikQuEeXNkDcG7

https://solscan.io/tx/TnpGiPKjyzZJU65NvH8UuY2eAprFkQtcYc2hkMiaPRBCGFGBHQY1sLXAxm2kPcurB86NePsaJhRMzuMK5FVbuNn

What Phantom Looks like -- 

<img width="1494" alt="Screen Shot 2022-04-25 at 2 23 12 PM" src="https://user-images.githubusercontent.com/98030332/165195818-acd9eb94-ed2e-48aa-ae28-94be289168e5.png">

**Comment by alchemistgo87** [comment]
This does work now!
