### ISSUE TITLE
Created NFTs in wallet not appearing on Profile

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#389]
There is an issue with profiles where they are not populating "created" NFTs that are clearly in the wallet. First noticed this happening with the SoulfulbySophie profile after delisting the Butterfly Art piece it no longer gave any option to relist and it would not show in "created" anymore.

This has been doing it on this profile -- 
![screenshot_2](https://user-images.githubusercontent.com/98030332/165359200-d8110880-a320-4243-9678-cd1a287218df.png)

![Screenshot_1](https://user-images.githubusercontent.com/98030332/165359237-e13aa501-5e26-4097-b843-98438d6b6fd4.png)

and on my personal profiles:

https://www.loom.com/share/1fbeb5874cdc456fbf4db3f1e4f760c3

**Comment by alchemistgo87** [comment]
This works now with the latest update!
