### ISSUE TITLE
Auction House link on NFT details is broken

### ISSUE THREAD

**Issue by dandlezzz** [holaplex/holaplex#423]
On this page, https://www.holaplex.dev/nfts/DDcZ5bRFopTAaehmEgF2LDWzrh2ypFCXiMEcD8V1vwP, the auction house link goes nowhere.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/5935947/167457556-610349e8-c6bf-4395-80fe-e3049581e9ce.png">

**Comment by kristianeboe** [comment]
Fixed
