### ISSUE TITLE
"Buy Now" Appearing on Profile while NFT is on Auction on Storefront

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#435]
This is weird: https://explorer.solana.com/address/7nnsqgKk2jqso96bqzKL3aRJZXuCHETAjsCxu97i97Q7
is showing up with buy now under created tab for the creators profile while its also on auction on their storefront.
https://dotsfordinner.holaplex.com/listings/8urADyS4GK9MG6cyES7fzJezD7ZyMnoLzzxQjUETRgGG
https://www.holaplex.com/nfts/4k6ibHVinWsESLLG3f58cyJpdHK1wH3QgXCpTWgkXcu

![auction](https://user-images.githubusercontent.com/98030332/168327148-de9d9616-dfe0-445c-9e13-ab9dc42c3df8.png)

![buynow](https://user-images.githubusercontent.com/98030332/168327179-277572ad-0105-4639-b018-8509b89f9ddf.png)

Error Message when trying to buy:

![error](https://user-images.githubusercontent.com/98030332/168327254-35709590-98b3-4b03-bd43-4189219b8fef.png)

**Comment by kristianeboe** [comment]
Ok, so we need to detect if the nft belongs to our auction house or not in order to show the buy now button

**Comment by kristianeboe** [comment]
We will soon sunset storefronts so this will not be prioritized.
