### ISSUE TITLE
Alpha bug(?): wallet I'm already following has "Follow" button

### ISSUE THREAD

**Issue by austinmilt** [holaplex/holaplex#438]
Wallet GgPpTKg78vmzgDtP1DNn72CHAYjRdKY7AV6zgszoHCSa

![Image](https://user-images.githubusercontent.com/1540936/168339021-4783f6ac-97a5-4d98-931a-87afb4b16895.png)

**Comment by austinmilt** [comment]
I see now that it is prompting me to follow someone else based on who I am follow. I think the button language is confusing, but maybe that's just me.

**Comment by kristianeboe** [comment]
Yes, Belle has some new designs for this :)
