### ISSUE TITLE
Collected Art Not Showing in Profile

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#440]
This art piece belongs to Alex but is not showing up in his collected section in profile

https://solscan.io/token/Ert6iy3f9YXNpeZ6358RGSiMP7uoxJRzpGC5xnzLj1YC

**Comment by kristianeboe** [comment]
![image](https://user-images.githubusercontent.com/10433154/169335497-1af6e8d0-ae0c-42c2-b1cf-998d9b5ec16b.png)
It is at the end now at least
