### ISSUE TITLE
Consolidated follow, create, and offer events

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#443]
~~And maybe modal~~

**Comment by bellebellesol** [comment]
**Follow events**

**Comment by bellebellesol** [comment]
Mint events

**Comment by bellebellesol** [comment]
# **Mint (Candy Machine) events**


**Example:** 


**Rules:**

**Comment by bellebellesol** [comment]
# Offer events - [Design](https://www.figma.com/file/3gdZ9t5zua4szl3LeRzujy/Alpha-MVP?node-id=649%3A5935)




**Rules:** 
Consolidate offer events when 3 or more occur chronologically and without interruption
