### ISSUE TITLE
Funds lost after retrying offers on profiles 

### ISSUE THREAD

**Issue by AbhisekBasu1** [holaplex/holaplex#461]
If someone makes an offer on any art in a storefront and then has to click retry, on both times the same amount of sol is deducted. But the offer itself doesn't increase, even though the same sol is deducted twice. 
Cancelling the offer only gives back their sol once. 

Test case with Max:

Max made an offer on an artwork of 0.5 sol - 

https://explorer.solana.com/tx/3PebPEvLk7gKjHaajCRXdM6sRpeikqfjHEHukJXFZHbvdLwXxt8s3iMhZt4tCiXntgNcwb5mKzyg2jqZm8ahAqgm

We could see in the blurry front end that the offer was accepted, but the loading pop up still showed the loading spinner, after which it showed retry. 

Max clicked on retry, and it took 0.5 sol again - 

https://explorer.solana.com/tx/4gmDvtMiZAgatezFjXZDD3FGm2AWqbhqZN1igWKsSGgRjb7H7YZqqEdGYitYq2xM41nb7wnUi4qkeBB1tb4g1GWD

The screen here should've reflected an offer of 1 sol (0.5 + 0.5) but it showed 0.5 sol still. 

Max clicked on cancel offer, expected to get back his entire amount, but he got back only 0.5 sol - 

https://explorer.solana.com/tx/4V8JSaB4kwUC4fNLmhRcJ5MwpvMp9TkeXGUSeUZYEHUHGXsdmPDaH4b9sZssVdRG9aXddyhdC427TREDaZxpSbix

At this point, the test case ends, but the front end still didn't update and showed a retry pop up again, clicking on which led to an infinitely loading pop-up

https://explorer.solana.com/tx/5NMngmwVuct65bZTyXGBpbu22x4bsnoVJeATZ2xT2SXRByBLd14JWmJzGkMTRmeNntJCZ6KE5YkUgHFPQ6HdKFQE

------
We have two different creators already facing this issue.

**Comment by milorue** [comment]
The first part of this is unavoidable as they made the transaction twice i'm assuming the first transaction failed or timed out but eventually went through, i can remove the retry if the tx timeout is hit?
