### ISSUE TITLE
Duplicate of NFT showing on scroll of Profile Page

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#481]
https://www.holaplex.com/profiles/7r8oBPs3vNqgqEG8gnyPWUPgWuScxXyUxtmoLd1bg17F/nfts

It is showing on Alex's wallet that he has 3 LANDSK NFTs in this profile when he only has two. When going to duplicate it shows the same NFT address(https://www.holaplex.com/nfts/DRvnUQm8qQNvEwBhc3A7iGoyd5MWUstw8aiETEZoxkZD). 

Graphql query returns only 2 nfts , the problem is with front-end

**Comment by alchemistgo87** [comment]
This issue does not exist now!
