### ISSUE TITLE
NFT not showing in profile

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#484]
This Ape -- https://www.holaplex.com/nfts/ETraLGcaKXvYE8n8j9dMf37L826QDt6EHgHneyRUjbEy // https://solscan.io/token/J5VbPurVRUwACydM8hLDUizqTRA5qV1w66oMoGSvVciJ

is not showing in Alex's Profile -- 

https://www.holaplex.com/profiles/7r8oBPs3vNqgqEG8gnyPWUPgWuScxXyUxtmoLd1bg17F/nfts

The GraphQL results show --

https://holaplex.slack.com/files/U02NAUQ2R36/F03GLBS4MCJ/image.png?origin_team=T02ERR4SW56&origin_channel=C02EUSTPGD7

**Comment by alchemistgo87** [comment]
It was fixed with other updates.
