### ISSUE TITLE
Collection support on creator profiles

### ISSUE THREAD

**Issue by bellebellesol** [holaplex/holaplex#505]
# Collection support on creator profiles - [Design](https://www.figma.com/file/DC1T92jSoSIw9rvvEJytNK/Profiles?node-id=6319%3A15826)

### **Collections tab on creator profiles**

**Candy Machine profile - collections tab**

![Image](https://user-images.githubusercontent.com/95664179/170312089-c6d60439-4b2e-41be-b1b1-aac9edaafe0c.png)

**1/1 Artist profile - collections tab**

![Image](https://user-images.githubusercontent.com/95664179/170312250-ebeecc21-4fe8-4624-8e2d-56fa50801b52.png)

**Comment by kristianeboe** [comment]
- [ ] Collections tab
- [ ] Collections card
