### ISSUE TITLE
Featured Collections

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#508]
A featured collections section on the home page

**Comment by kespinola** [comment]
### Query Options

Separate query roots per category
```graphql
collectionsByVolume(search: "DeGods", startDate: "{NOW}", endDate: "{7 Days Away}", orderBy: "DESC|ASC") {
  name
  imageUrl
  nftCount
  floorPrice
}
collectionsByMarketcap(search: "DeGods", startDate: "{NOW}" endDate: "{7 Days Away}", orderBy: "DESC|ASC") {
  name
  imageUrl
  nftCount
  floorPrice
}
```

Single collections query root with argument of "category"

```graphql
collections(search: "DeGods", startDate: "{NOW}", endDate: "{7 Days Away}", category: "MARKETCAP|VOL", orderBy: "DESC|ASC", priceMin: 1000, priceMax:  10000) {
  name
  imageUrl
  nftCount
  floorPrice
}
```

Top VOL Query
```sql
SELECT SUM(price), metadatas.collection  FROM purchases
INNER JOIN metadatas metadatas ON (purchases.metadata = metadatas.address)
INNER JOIN metadatas collections ON (metdatas.collection = metadatas.address)
WHERE purchases.created <= "24h, 7d, 30d"
GROUP BY metadatas.collection
```

Top Marketcap
```sql
SELECT SUM(prices), 
```

----

```graphql
purchases(startDate: "now", endDate: "") {
  price
  nft {
     name
     mintAddress
    
   }
}
```

**Comment by kristianeboe** [comment]
From Notion
- Adding HOT collections to [[holaplex.com](http://holaplex.com/)](http://holaplex.com/) -  [[Design i have is for:](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)
    - [['new and notable collections'](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)
    - [['top volume collections'](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)
    - [['top marketcap collections' with the associated sorting options for these in the discover page collections tab](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)
