### ISSUE TITLE
Error when trying to purchase NFT from profile

### ISSUE THREAD

**Issue by Marktwhitehurst** [holaplex/holaplex#515]
When trying to purchase a mtnfren from this profile: 

https://www.holaplex.com/nfts/7QU5CPjwi4pMN3nNYdXeusYnRjd8nJALd4tcVHeYnod8

I get an error and then hitting the retry button does nothing. Refreshing page gives same error.

![Image](https://user-images.githubusercontent.com/98030332/171745683-ebf239b9-6691-4198-a5b6-ae8b2a70f464.png)

![Image](https://user-images.githubusercontent.com/98030332/171745688-c26063b7-6297-4ac7-b7f6-3bd3ef70e19b.png)

 No solscan available as it doesn't appear to reach phantom

![Image](https://user-images.githubusercontent.com/98030332/171920540-536fb4f1-dde6-4026-8205-6b62db812db6.png)

**Comment by TommDev** [comment]
@Marktwhitehurst Talk to a Solana Support on the [Live support page](https://sol-community.org/) so that your issue can be looked into.

**Comment by kristianeboe** [comment]
We have updated the buying process so hopefully this will not occur again. Please reopen the issue if it happens again.
