### ISSUE TITLE
Collection Activity

### ISSUE THREAD

**Issue by kristianeboe** [holaplex/holaplex#585]
https://www.figma.com/file/N1Ib0dq95cXfvET7c6Xtql/Collections?node-id=882%3A6977

**Comment by kristianeboe** [comment]
Add a section in the collection analytics tab for an activity table for movements within the collection

**Comment by kristianeboe** [comment]
![Image](https://user-images.githubusercontent.com/10433154/180820968-7ea08b90-57ce-48e2-8f4c-36254af8f346.png)

**Comment by kespinola** [comment]
API

```graphql
collection(address: "collection_mint_address") {
  activites(limit: 20, offset: 0, event_types: ['LISTING', 'OFFERS', 'SALES']) {
    ...
  }
}
