### ISSUE TITLE
Add Activity to NFT Details page

### ISSUE THREAD

**Issue by milorue** [holaplex/holaplex#607]
Add listing, sale, offer activity to the NFT details page

**Comment by damianr** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/260165/179579202-396a181b-9272-4866-867b-6ffff4ed008b.png">

**Comment by dandlezzz** [comment]
@damianr does an offer count as an activity? Is that a bid?

**Comment by damianr** [comment]
Yeah, let's use "Offer made" instead of "Bid placed". Will we also have "offer canceled" event? Also I think we should do "offer accepted" instead of "sold" if it was from an offer, can we differentiate those?
