### ISSUE TITLE
Discovery + Collections Cleanups

### ISSUE THREAD

**Issue by bellebellesol** [holaplex/holaplex#643]
## **[Discovery](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)**

- [x]  Remove standalone 'Alpha' link from nav so it only appears once, inside the new discover dropdown menu
- [x]  Tighten up horizontal alignment of icons and their respective labels in dropdown menu. Icons look slightly too raised, should be aligned with the pink lines: 
![Image](https://user-images.githubusercontent.com/95664179/180430205-83447f75-618f-4df9-8823-a42014caf80c.png)

- [x] Implement a few new design changes to tabs/searchbar area (view design in figma). This keeps tabs in the same position regardless of filter panel being expanded or collapsed and feels cleaner, akin to OpenSea and Rarible's explore pages
Filter collapsed:
![Image](https://user-images.githubusercontent.com/95664179/180460804-0be09cb1-0c6f-4820-ad59-727015f41b41.png)
Filter expanded:
![Image](https://user-images.githubusercontent.com/95664179/180460837-25a7d77d-e576-4438-a110-ac72b0c2cd4f.png)

- [x] Tighten up styling around the search bar and sorting dropdown menus. Small deviations from design such as search bar width, expanded dropdown styling etc. 
If its simple and quick, add the active sort item to the top of the dropdown list with a check mark to show its selected currently.

Currently looks like:
![Image](https://user-images.githubusercontent.com/95664179/180434922-041da27c-5f89-4a99-a9df-965a7e199067.png)
![Image](https://user-images.githubusercontent.com/95664179/180434935-b3892d8c-689f-49ad-bb90-3e15156d1147.png)
![Image](https://user-images.githubusercontent.com/95664179/180434936-66f28b62-c078-404a-a8a7-cef644c8d9e0.png)

Should look like:
![Image](https://user-images.githubusercontent.com/95664179/180461226-3c044c27-dbab-47fa-83e2-7599752843cf.png)
![Image](https://user-images.githubusercontent.com/95664179/180435024-f3a18015-9dfb-4a7e-a554-180b48b0bab1.png)
![Image](https://user-images.githubusercontent.com/95664179/180435025-82bba337-4869-443a-bfc0-e962c4eb5ba7.png)

- [x] Adjustments to the layout switcher (pic for context):
![Image](https://user-images.githubusercontent.com/95664179/180438661-dc014483-d835-461c-9629-97105fc9715b.png)
a) Change the minimized layout to be rows of 4 items for the collections and NFTs tabs
b) Change the enlarged layout to be rows of 3 items for the collections and NFTs tabs
c) If viewing the NFTs tab in minimized layout, switch to the enlarged layout when the filter panel is expanded to allow space.

- [x] Sorting dropdowns should open and close on click not on hover. If theres no solid reason for using hover here  I think we should make them open on click - quite common for dropdown select menus

- [x] Add a snappy but smooth transition for opening and closing dropdowns + filter panel

## **[Collections](https://www.figma.com/file/N1Ib0dq95cXfvET7c6Xtql/Collections?node-id=1%3A3518)**

- [x] Show collection supply and floor price in labels along the bottom of collection cards ([view in figma](https://www.figma.com/file/tNPfdIHmoevsnKcc8dPMz2/Home-V2?node-id=2353%3A8419)):
![Image](https://user-images.githubusercontent.com/95664179/180432006-df425b63-f437-4187-8ebc-75a28aeba784.png)
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]  
- [ ]

**Comment by kespinola** [comment]
I'm going to take a crack at these.

**Comment by kespinola** [comment]
<img width="305" alt="Screen Shot 2022-07-27 at 11 20 06 AM" src="https://user-images.githubusercontent.com/2388118/181211508-e88a5e03-07b6-4393-a48e-e5337cdf4f49.png">

Aligned discover items center.
